name: ferry_request_id_link
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ferry: ^0.10.1-0.1.nullsafety.0
  uuid: ^3.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
